name: DevR Pipeline

on:
  push:
    branches: [ devR ]

permissions:
  contents: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest --tb=short -q
        
    - name: Test coverage check
      run: |
        RESULT=$(python -m pytest --tb=no -q | tail -1)
        if [[ $RESULT != *"passed"* ]] || [[ $RESULT == *"failed"* ]]; then
          echo "Tests failed: $RESULT"
          exit 1
        fi
        echo "All tests passed: $RESULT"

  deploy-devr:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Deploy to DevR Heroku
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: |
        git remote add heroku-devr https://:${HEROKU_API_KEY}@git.heroku.com/mystocktrackerapp-devr.git
        git push heroku-devr HEAD:main --force
    
    - name: Verify DevR Deployment
      continue-on-error: true
      run: |
        chmod +x scripts/verify_deployment.sh
        ./scripts/verify_deployment.sh devr || echo "⚠️ Verification failed but deployment may still be successful - check manually"

  promote-to-main:
    needs: [test, deploy-devr]
    runs-on: ubuntu-latest
    environment: production
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{secrets.GITHUB_TOKEN}}
        persist-credentials: true
    
    - name: Merge devR to main and deploy
      run: |
        git config --global user.name 'GitHub Actions'
        git config --global user.email 'actions@github.com'
        git checkout main
        git pull origin main
        git merge devR --no-ff -m "Auto-merge devR to main after UAT approval"
        git push https://${{secrets.GITHUB_TOKEN}}@github.com/craigrow/MyStockTrackerApp.git main
    
    - name: Deploy to Production Heroku
      env:
        HEROKU_API_KEY: ${{secrets.HEROKU_API_KEY}}
      run: |
        git remote add heroku-prod https://:${HEROKU_API_KEY}@git.heroku.com/mystocktrackerapp-prod.git
        git push heroku-prod HEAD:main --force
    
    - name: Verify Production Deployment
      continue-on-error: true
      run: |
        chmod +x scripts/verify_deployment.sh
        ./scripts/verify_deployment.sh prod || echo "⚠️ Verification failed but deployment may still be successful - check manually"